### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Snownee** [ZengineeringTeam/Foundry#1]
- [x] 注册方式改为事件
- [x] 支持流体容器输入机器
- [x] 流体: 铬 铱 钴 钛 精炼铁
- [x] 更多TF工具的模具支持
- [x] GUI I18N
- [x] GUI 添加查看 JEI 按钮
- [x] 重设流体颜色
- [x] 热量损失计算
- [ ] 重写Router，使其不再依赖tick

**Comment by SihenZhang** [comment]
- [x] 熔岩加热炉

**Comment by Snownee** [comment]
@SihenZhang 忘了这条了。

目前的打算是这样的：
能量炉子：消耗大量能量
熔岩炉子：消耗燃料和少量能量

**Comment by SihenZhang** [comment]
请定义`大量`和`少量`
BTW，熔岩炉子可以做 Thermal Foundation 的烈焰之炽焱的支持，然后熔岩和烈焰之炽焱所能提供的最高温度不同……
其实上面这条不适用于咱们整合包，因为咱们整合包 TE 被放在了后期，那时候根本用不上 Foundry 了，最好的还是比如做个 CrT 支持啊这样子，但感觉成本不小……
以及熔岩炉子消耗能量……能不能加个 cfg 做个主动关掉这样子……
（我总感觉我在替其他的可能用你魔改版的 Foundry 的整合包作者着想）

**Comment by Snownee** [comment]
大量：比目前的炉子高出至少两倍，因为加热本来就是很耗电的事情
CrT支持：计划中
如果你觉得不需要能量我就不写了还省事

**Comment by SihenZhang** [comment]
为啥说不需要能量呢？因为那个时候可能没有能量……
耗能高点我是支持的
