### ISSUE TITLE
Built-in recipes not removed from JEI

### ISSUE THREAD

**Issue by ghost** [ZengineeringTeam/Foundry#16]
When I remove certain tools from the game in the cofh-config file (e.g. copper tools) their casting recipes ares till visible in JEI and trying to remove them with Casting.removeRecipe results in an error.

**Comment by ghost** [comment]
Sorry, I'm a big idiot. The reason it didn't work was because I made a mistake in the removeRecipe method. So it is possible to remove them with crafttweaker. Sorry.

**Comment by Snownee** [comment]
They should be removed if you already disabled their tools, I am fixing this.
