### ISSUE TITLE
Potential for making Thermal Foundation optional dependency

### ISSUE THREAD

**Issue by SimonMeskens** [ZengineeringTeam/Foundry#18]
I'd been thinking of forking Foundry myself to pull out the Thermal Foundation dependency. This new fork does everything I want except for that it seems. Do you think we could make that happen?

**Comment by Snownee** [comment]
Do you mean sending a PR or forking a new edition?

**Comment by SimonMeskens** [comment]
I could certainly work on a PR myself. The issue is simple: I want to make a pack that revolves around Ceramics, Tinker's Construct and Tinker's Complement and those already provide their own set of liquid metals, so I see no sense in adding Thermal Foundation to the pack for no reason. I looked at the code and I think TF is used only for recipes, right? I could make all the code paths using TF optional and that should work with minor code changes. 

Then all that would be needed is for a fallback module for the recipes that tries to fallback on oredicted materials first, then if none are present, vanilla. For example: cupronickel -> oredict cupronickel -> oredict constantan -> gold

**Comment by SimonMeskens** [comment]
I don't feel like maintaining a fork, so I'm mainly wondering if you'd be interested in pulling in such a PR to the main repo here.

**Comment by Snownee** [comment]
Yes, I am willing to do this 😄

**Comment by SimonMeskens** [comment]
I just saw that you did the move to mod integrations and fallback recipes. What a stellar job!

The only thing else I can think of is to write a system for only adding molten liquids for metals which have ores. I tried adding this to my previous PR, but I ran into some loading order issues, so I didn't get it done in time.
