### ISSUE TITLE
Inspirations Cauldron Support?

### ISSUE THREAD

**Issue by ManMan36** [ZengineeringTeam/Foundry#35]
The mod Inspirations adds custom recipes to the cauldron. Would it be possible to have those tweaks be compatible with the Bronze Cauldron this mod adds?

**Comment by Snownee** [comment]
Please report to Inspirations.

**Comment by ManMan36** [comment]
I reported this to Inspirations. [This](https://github.com/KnightMiner/Inspirations/issues/102#issuecomment-450037454) was their response.

**Comment by Snownee** [comment]
Thanks for your suggestion, but I noticed the license used by Inspirations is incompatible with LGPLv3 so sorry.
