### ISSUE TITLE
Metal Caster doesn't work without RF

### ISSUE THREAD

**Issue by dredhorse** [ZengineeringTeam/Foundry#37]
Hi, I have RF disabled, several Buckets of copper in the Metal Caster, a Block Mold, but nothing happens.

Any idea?

**Comment by Snownee** [comment]
![image](https://user-images.githubusercontent.com/16059084/50650703-2e813a00-0fbc-11e9-885d-b6a318a5fc3e.png)
Can not reproduce

**Comment by dredhorse** [comment]
hmm, will try it again... modpack in question https://minecraft.curseforge.com/projects/off-the-beaten-path
did you try the mod alone? there is only the Metal Caster required or?

**Comment by Snownee** [comment]
I don't know what you mean

**Comment by liach** [comment]
I think snownee means that without rf, metal casters still require forge energy.

**Comment by Snownee** [comment]
@liach No it does not require any energy. And RF has built-in FE support right?

**Comment by dredhorse** [comment]
well, I grab a metal caster from JEI, place it in the world, add copper and a mold and it does this:

<img src="https://monosnap.com/image/eMoAhgw4HT2V6DV45pUeDmpJibRFYn.png">

I use my own modpack, OffTheBeatenPath and disabled Energy.

**Comment by dredhorse** [comment]
btw: this is copper from embers

**Comment by Snownee** [comment]
![image](https://user-images.githubusercontent.com/16059084/50686714-6e4a2f00-1059-11e9-8664-0b0ce07c9824.png)
can not reproduce

**Comment by dredhorse** [comment]
hmm, perhaps because the tooltip is wrong?

<img src="https://monosnap.com/image/z9gdlOILNyxFcTZ8eEh5jM8uXuDlJk.png">

the code says that if the metal caster doesn't require RF it shouldn't display the text.

(The Red ToolTip was done by Crafttweaker).

**Comment by Snownee** [comment]
Yes it is wrong

**Comment by dredhorse** [comment]
so I tested this with only jei, ceramics and zen:foundry.

Is does NOT work on my end, could you please check again?

@Snownee

**Comment by Snownee** [comment]
So if you do not have a mod that registers copper block, it definitely won't work

**Comment by dredhorse** [comment]
facepalm, ok, installed embers rekindled, worked.
But the icon still specifies that it requires RF, so there is some bug as it seems.
installed unidict, worked
installed oresalleasy, worked.
The Copper Block and the liquid is from Embers Rekindled.
In my modpack the copper block is from chisel. Added that, it worked.
I guess if you don't have an idea I would need to install now mod by mod and check :-(

**Comment by dredhorse** [comment]
oh, and I have 2 recipes directly beneath each other in my modpack with the same ingredients.

**Comment by dredhorse** [comment]
any idea on how to tackle the issue?

**Comment by Snownee** [comment]
I do not know what you mean. Please describe more specifically

**Comment by dredhorse** [comment]
do you have an idea which mod could cause that issue? I tried it with just some base mods as described above, and that works.
So it looks like mod interaction issue, but I have no idea which one could cause it.
I also have a crash with The One Probe which only happens on a server and it is also pointing into mod interoperability.

**Comment by dredhorse** [comment]
could it be that the code in https://github.com/ZengineeringTeam/Foundry/blob/zen/src/main/java/exter/foundry/tileentity/TileEntityMetalCaster.java  doesn't detect a valid recipe even if jei shows it?

**Comment by Snownee** [comment]
I really do not know what your issue is

**Comment by dredhorse** [comment]
language barrier I guess:

In my modpack (see above) there seems to be a mod interaction issue with ZEN:Foundry.
With RF disabled the MetalCaster doesn't cast.
I haven't tried with RF enabled.
As we both know it works with limited mods.
The problem I have is that I can not test every single mod to figure out which mod is breaking Zen:Foundry.
I'm asking for help to figure out which mod it could be or if there is perhaps an issue with the code which is causing that behavior.

**Comment by Snownee** [comment]
> I haven't tried with RF enabled.

Why not try it?

**Comment by dredhorse** [comment]
ok, tried that... something fishy... the FE meter says 0, oneprobe does show 40 K RF.

<img src="https://monosnap.com/image/pmRX0NIhtF3aGyp5uAwBJPFr6rVfcU.png">

still no casting

**Comment by Snownee** [comment]
Try powering it. If it still no casting so it is not a issue with RF.

Then make sure here is a specific recipe in JEI and use some tool to make sure the output item has the ore dictionary entry.

**Comment by dredhorse** [comment]
it is powered, I don't have any of the standard RF mods though like I said... oneprobe shows that the caster has power, the caster itself not

**Comment by Inbalurgator** [comment]
> it is powered, I don't have any of the standard RF mods though like I said... oneprobe shows that the caster has power, the caster itself not

i found that without Base Metals,it wont work
