### ISSUE TITLE
Buckets from ceramics consumed in the crucible

### ISSUE THREAD

**Issue by Zergmazter** [ZengineeringTeam/Foundry#39]
Version 1.7.4

Whenever I place a ceramic bucket of any molten material in any of the crucibles, the material is deposited in the crucible but the bucket is consumed. I tried this with the vanilla bucket, and an empty bucket is returned in the output slot.

Let me know if this is on your end or ceramics end, so that I can report this accordingly please.

**Comment by Snownee** [comment]
Please read this: https://minecraft.curseforge.com/projects/ceramics

**Comment by Zergmazter** [comment]
Sorry I forgot about that part in the ceramics mod. Thank you for the info.
