### ISSUE TITLE
[Compat] Recipes for Base Metals suite incomplete

### ISSUE THREAD

**Issue by Dragnier** [ZengineeringTeam/Foundry#42]
I see blocks (stairs and such), nuggets, ingots, rods, etc. working properly in the metal caster. However, the tools and armors do not cast.

For example, molten silver in the metal caster with a pickaxe mold and sticks will not cast a Base Metals silver pickaxe.

Further, there are not molten versions for the Base Metals Suite exclusive metals such as Star-Steel and Adamantite which causes none of their casting recipes to work since you can't even melt them.

**Comment by Snownee** [comment]
> For example, molten silver in the metal caster with a pickaxe mold and sticks will not cast a Base Metals silver pickaxe.

![image](https://user-images.githubusercontent.com/16059084/50870944-0ac35700-13f5-11e9-8f48-5009c38b7092.png)

> Further, there are not molten versions for the Base Metals Suite exclusive metals such as Star-Steel and Adamantite which causes none of their casting recipes to work since you can't even melt them.

![image](https://user-images.githubusercontent.com/16059084/50870987-2af31600-13f5-11e9-845e-00c694f57d7f.png)

![image](https://user-images.githubusercontent.com/16059084/50871010-40684000-13f5-11e9-8013-fa534b97d79d.png)

**Comment by Dragnier** [comment]
I apologize. I updated your mod in Curse but for some reason it did not update properly and still loaded the previous version. This was entirely a Curse Launcher update error.
