### ISSUE TITLE
Mold JEI Recipes

### ISSUE THREAD

**Issue by Dragnier** [ZengineeringTeam/Foundry#45]
Some molds like the ingot are somewhat easy to guess at the recipe in the mold maker. Others, like the gear, are not. It would be nice to have the option to see the recipes for them in JEI.

**Comment by Snownee** [comment]
You can already do that

**Comment by Dragnier** [comment]
Ummm... not in the current version I have. I click on the molds and nothing shows. It literally does nothing when I click on them or hit R on one I got from the creative menu.

[![](https://img.youtube.com/vi/vGpaaPKoTqQ/0.jpg)](http://www.youtube.com/watch?v=vGpaaPKoTqQ "Click to play on Youtube.com")


Zen: Foundry- 1.7.7
Forge - 14.23.5.2807

**Comment by Snownee** [comment]
I have updated Zen: Foundry. Better check if this issue still occurs

**Comment by Dragnier** [comment]
Seems fixed.
