### ISSUE TITLE
Embers in General

### ISSUE THREAD

**Issue by Fortist** [ZengineeringTeam/Foundry#50]
While flipping through the recipes, I realized that every molten metal that embers takes over (Iron, Gold, Bronze, etc) messes up all related melting recipes, in the way that Iron melts at 900, Bronze melts at 900, gold melts at 900, etc.
Even stuff like Armor and Tools, all melt at 900.
Im gonna try some Unidict, JAOPCA, and Foundry "Mod Priorities" stuff and see what takes, if at all.

**Comment by Snownee** [comment]
I can make Foundry take over liquids from Embers but I do not think this is a sustainable approach..
