### ISSUE TITLE
Crafttweaker ILiquidDefinition

### ISSUE THREAD

**Issue by Fortist** [ZengineeringTeam/Foundry#52]
So, Im trying to add/change the fluid fuels for the heater and Im getting an error looking for **Definition** instead of **Stack**

At least, I have no idea how to use Definition, yet.
Here is the script
`FluidHeater.addFuel(<liquid:lava>, 210000);`
(I imported the mods.foundry.* stuff)

Usually this works for most mods that use liquids, but this one asks for definitions, and Im currently reading about what exactly that is.

oh and here is the error, giving me the exact issue

> addFuel(ZenTypeNative: crafttweaker.liquid.ILiquidDefinition, int)
> addFuel(ZenTypeNative: crafttweaker.liquid.ILiquidDefinition)

**Comment by Snownee** [comment]
Did you `import crafttweaker.liquid.ILiquidDefinition`?

If it still does not work, use `<liquid:lava>.definition`

**Comment by Fortist** [comment]
I did, but I didnt know what to do with it. 
Ill try adding that and see if it works.

**Comment by Fortist** [comment]
That seems to make it work.
 
I have other issues that I'd like to bring up then.
Clearing the Melting recipes removes all recipes. Any recipes that I try to replace dont get recognized, but it doesnt throw an error.
For example, I add a copper ore melting recipe, in game, I cant melt it at all.
But, my non-foundry fluid recipes seem to work (JAOPCA)
Disabling the fluids in the config seems to fix this break, as now copper ore will melt.
Recipes for reference
```
Melting.clear();
Melting.addRecipe(<liquid:copper>*288, <ore:oreCopper>, 1200, 400);
Melting.addRecipe(<liquid:tin>*288, <ore:oreTin>, 600, 400);
Melting.addRecipe(<liquid:mithril>*288, <ore:oreMithril>, 3800, 400);
```

Mithril works, as it has no foundry fluid.
Copper and tin do not work with the config having them enabled, disabling them makes the recipes work, however.

**Comment by Fortist** [comment]
You know what, this is too large an undertaking to try and edit the melt times for everything so Im just gonna ask for this instead;
Configurable melting times per item type?
Ergo, Dusts are faster to melt down than straight ores, blocks take the longest to melt down, etc.
Otherwise I have to do something like this for every ore, while fixing the alloying recipes, and adding every armor and tool recipe.
```
Melting.addRecipe(<liquid:iron>*288, <ore:oreIron>, 1600, 400);
Melting.addRecipe(<liquid:iron>*1296, <ore:blockIron>, 1600, 200);
Melting.addRecipe(<liquid:iron>*144, <ore:dustIron>, 1600, 800);
Melting.addRecipe(<liquid:iron>*144, <ore:ingotIron>, 1600, 400);
Melting.addRecipe(<liquid:iron>*144, <ore:plateIron>, 1600, 400);
Melting.addRecipe(<liquid:iron>*576, <ore:gearIron>, 1600, 400);
Melting.addRecipe(<liquid:iron>*11, <ore:nuggetIron>, 1600, 600);
```

Im too stupid to figure out Arrays in this instance.
