### ISSUE TITLE
Config for how quickly temperature rises in melting crucible

### ISSUE THREAD

**Issue by dariusfontan** [ZengineeringTeam/Foundry#53]
Hi there,
love this fork of the foundry, thanks for the great work!
I noticed that the temperature in the melting crucible is rising very fast, when adding fuel to the 
burner heater below it. It's operative in just seconds.
In the original mod this took a little longer, which I  found better and more realistic.
Could you add a config for the time it takes to biuld up temperature in the melting crucible ?
Or maybe there already is one and I haven't found it yet ?
Thank you!

**Comment by Snownee** [comment]
Added in 1.7.16
