### ISSUE TITLE
Error with TFC 1.12.2 port.

### ISSUE THREAD

**Issue by samuelt005** [ZengineeringTeam/Foundry#56]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  ForgelinPlugin (Forgelin-1.8.3.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.5-1.12.2.jar)
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  BetterFoliageLoader (BetterFoliage-MC1.12-2.2.0.jar)
  MovingWorldCore (movingworld-1.12-6.342-full.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  LoadingPlugin (BetterWithLib-1.12-1.5.jar)
Contact their authors BEFORE contacting forge

// I'm sorry, Dave.

Time: 7/9/19 6:49 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Zen: Foundry (foundry)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 32767
	at net.dries007.tfc.objects.Gem$Grade.fromMeta(Gem.java:34)
	at net.dries007.tfc.objects.items.ItemGem.getGradeFromStack(ItemGem.java:57)
	at net.dries007.tfc.objects.items.ItemGem.func_77667_c(ItemGem.java:63)
	at net.minecraft.item.ItemStack.func_77977_a(ItemStack.java:509)
	at exter.foundry.util.hashstack.HashableItem.hashCode(HashableItem.java:76)
	at java.util.HashMap.hash(Unknown Source)
	at java.util.HashMap.put(Unknown Source)
	at exter.foundry.material.MaterialRegistry.registerItem(MaterialRegistry.java:86)
	at exter.foundry.init.InitRecipes.postInit(InitRecipes.java:56)
	at exter.foundry.Foundry.postInit(Foundry.java:127)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_211, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 724631672 bytes (691 MB) / 2286419968 bytes (2180 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx4096m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 61 mods loaded, 61 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                                           | Version           | Source                                             | Signature                                |
	|:----- |:-------------------------------------------- |:----------------- |:-------------------------------------------------- |:---------------------------------------- |
	| LCHIJ | minecraft                                    | 1.12.2            | minecraft.jar                                      | None                                     |
	| LCHIJ | mcp                                          | 9.42              | minecraft.jar                                      | None                                     |
	| LCHIJ | FML                                          | 8.0.99.99         | forge-1.12.2-14.23.5.2838-universal.jar            | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJ | forge                                        | 14.23.5.2838      | forge-1.12.2-14.23.5.2838-universal.jar            | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJ | com.elytradev.movingworld.common.asm.coremod |                   | minecraft.jar                                      | None                                     |
	| LCHIJ | foamfixcore                                  | 7.7.4             | minecraft.jar                                      | None                                     |
	| LCHIJ | engineersdecor                               | 1.0.8             | engineersdecor-1.12.2-1.0.8.jar                    | ed58ed655893ced6280650866985abcae2bf7559 |
	| LCHIJ | crafttweaker                                 | 4.1.19            | CraftTweaker2-1.12-4.1.19.jar                      | None                                     |
	| LCHIJ | mtlib                                        | 3.0.6             | MTLib-3.0.6.jar                                    | None                                     |
	| LCHIJ | modtweaker                                   | 4.0.17            | modtweaker-4.0.17.jar                              | None                                     |
	| LCHIJ | jei                                          | 4.15.0.268        | jei_1.12.2-4.15.0.268.jar                          | None                                     |
	| LCHIJ | railcraft                                    | 12.0.0            | railcraft-12.0.0.jar                               | a0c255ac501b2749537d5824bb0f0588bf0320fa |
	| LCHIJ | redstoneflux                                 | 2.1.0             | RedstoneFlux-1.12-2.1.0.6-universal.jar            | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJ | cofhcore                                     | 4.6.3             | CoFHCore-1.12.2-4.6.3.27-universal.jar             | None                                     |
	| LCHIJ | cofhworld                                    | 1.3.1             | CoFHWorld-1.12.2-1.3.1.7-universal.jar             | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJ | thermalfoundation                            | 2.6.3             | ThermalFoundation-1.12.2-2.6.3.27-universal.jar    | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJ | immersiveengineering                         | 0.12-89           | ImmersiveEngineering-0.12-89.jar                   | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| LCHIJ | alternatingflux                              | 0.12.2-2          | alternatingflux-0.12.2-2.jar                       | None                                     |
	| LCHIJ | astikorcarts                                 | 1.12.2-0.1.2.7    | astikorcarts-1.12.2-0.1.2.7.jar                    | None                                     |
	| LCHIJ | base                                         | 3.13.0            | base-1.12.2-3.13.0.jar                             | None                                     |
	| LCHIJ | forgelin                                     | 1.8.3             | Forgelin-1.8.3.jar                                 | None                                     |
	| LCHIJ | betterfoliage                                | 2.2.0             | BetterFoliage-MC1.12-2.2.0.jar                     | None                                     |
	| LCHIJ | betterstorage                                | 3.0.0.2           | BetterStorageToo-1.12.2-3.0.0.2.jar                | None                                     |
	| LCHIJ | betterwithlib                                | ${version}        | BetterWithLib-1.12-1.5.jar                         | None                                     |
	| LCHIJ | ctm                                          | MC1.12.2-0.3.3.22 | CTM-MC1.12.2-0.3.3.22.jar                          | None                                     |
	| LCHIJ | reborncore                                   | 3.13.12.447       | RebornCore-1.12.2-3.13.12.447-universal.jar        | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
	| LCHIJ | techreborn                                   | 2.22.1.979        | TechReborn-1.12.2-2.22.1.979-universal.jar         | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
	| LCHIJ | betterwithmods                               | 1.12-2.3.20-1027  | BetterWithMods-1.12-2.3.20-1027.jar                | None                                     |
	| LCHIJ | ceramics                                     | 1.12-1.3.7        | Ceramics-1.12-1.3.7.jar                            | None                                     |
	| LCHIJ | contenttweaker                               | 1.12.2-4.9.1      | ContentTweaker-1.12.2-4.9.1.jar                    | None                                     |
	| LCHIJ | cosmeticarmorreworked                        | 1.12.2-v4a        | CosmeticArmorReworked-1.12.2-v4a.jar               | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
	| LCHIJ | ctgui                                        | 1.0.0             | CraftTweaker2-1.12-4.1.19.jar                      | None                                     |
	| LCHIJ | crafttweakerjei                              | 2.0.3             | CraftTweaker2-1.12-4.1.19.jar                      | None                                     |
	| LCHIJ | movingworld                                  | 1.12-6.342        | movingworld-1.12-6.342-full.jar                    | None                                     |
	| LCHIJ | davincisvessels                              | @DVESSELSVER@     | davincisvessels-1.12-6.340-full.jar                | None                                     |
	| LCHIJ | earthworks                                   | 1.3.4.3           | Earthworks-1.12-1.3.6.jar                          | None                                     |
	| LCHIJ | engineersdoors                               | 0.8.0             | engineers_doors-1.12.2-0.8.0.jar                   | None                                     |
	| LCHIJ | finite-water-control                         | 1.0               | finite-water-control-1.12-1.0.jar                  | None                                     |
	| LCHIJ | foamfix                                      | 0.10.5-1.12.2     | foamfix-0.10.5-1.12.2.jar                          | None                                     |
	| LCHIJ | waila                                        | 1.8.26            | Hwyla-1.8.26-B41_1.12.2.jar                        | None                                     |
	| LCHIJ | immersivecables                              | 1.3.2             | ImmersiveCables-1.12.2-1.3.2.jar                   | None                                     |
	| LCHIJ | immersivepetroleum                           | 1.1.9             | immersivepetroleum-1.12.2-1.1.9.jar                | None                                     |
	| LCHIJ | immersiveposts                               | 0.1.2             | ImmersivePosts-0.1.2.jar                           | 0ba25d8c0ec23537afc6db926e1ea764335a33b1 |
	| LCHIJ | immersivetech                                | 1.3.10            | immersivetech-1.12-1.3.10.jar                      | None                                     |
	| LCHIJ | journeymap                                   | 1.12.2-5.5.4      | journeymap-1.12.2-5.5.4.jar                        | None                                     |
	| LCHIJ | justenoughpetroleum                          | 0.1               | JustEnoughPetroleum-0.1.jar                        | None                                     |
	| LCHIJ | magneticraft                                 | 3.4.5             | Magneticraft_1.12-2.6.5-dev.jar                    | None                                     |
	| LCHIJ | mtrm                                         | 1.2.2.30          | MineTweakerRecipeMaker-1.12.2-1.2.2.30.jar         | None                                     |
	| LCHIJ | modelloader                                  | 1.1.6             | modelloader-1.1.6.jar                              | None                                     |
	| LCHIJ | modularmachinery                             | 1.10.0            | modularmachinery-1.12.2-1.10.0.jar                 | a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 |
	| LCHIJ | norecipebook                                 | 1.2.1             | noRecipeBook_v1.2.2formc1.12.2.jar                 | None                                     |
	| LCHIJ | placebo                                      | 1.6.0             | Placebo-1.12.2-1.6.0.jar                           | None                                     |
	| LCHIJ | pneumaticcraft                               | 1.12.2-0.11.3-366 | pneumaticcraft-repressurized-1.12.2-0.11.3-366.jar | None                                     |
	| LCHIJ | resourceloader                               | 1.5.3             | ResourceLoader-MC1.12.1-1.5.3.jar                  | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| LCHIJ | tfc                                          | ${version}        | TerraFirmaCraft-MC1.12.2-0.10.0.48.jar             | None                                     |
	| LCHIJ | toastcontrol                                 | 1.8.1             | Toast+Control-1.12.2-1.8.1.jar                     | None                                     |
	| LCHIJ | watercontrolextreme                          | 1.0.0             | WaterControlExtreme-1.0.2.jar                      | None                                     |
	| LCHIJ | wearablebackpacks                            | 3.1.3             | WearableBackpacks-1.12.2-3.1.3.jar                 | None                                     |
	| LCHIE | foundry                                      | 1.7.12            | ZenFoundry-1.7.12.jar                              | None                                     |
	| LCHI  | orelib                                       | 3.5.2.2           | OreLib-1.12.2-3.5.2.2.jar                          | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCHI  | techreborn_compat                            | 1.0.0             | TechReborn-ModCompatibility-1.12.2-1.1.0.38.jar    | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |

	Loaded coremods (and transformers): 
ForgelinPlugin (Forgelin-1.8.3.jar)
  
IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.5-1.12.2.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  lumien.resourceloader.asm.ClassTransformer
BetterFoliageLoader (BetterFoliage-MC1.12-2.2.0.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
MovingWorldCore (movingworld-1.12-6.342-full.jar)
  
CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  team.chisel.ctm.client.asm.CTMTransformer
LoadingPlugin (BetterWithLib-1.12-1.5.jar)
  betterwithmods.library.core.ClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 430.86' Renderer: 'GeForce GTX 1060 6GB/PCIe/SSE2'
	TerraFirmaCraft: You are not running an official build. Please do not use this and then report bugs or issues.
	RebornCore: 
		Plugin Engine: 0
		RebornCore Version: 3.13.12.447
		Runtime Debofucsation 1
		RenderEngine: 0

**Comment by Snownee** [comment]
Fixed in 1.7.13
