### ISSUE TITLE
[Suggestion]1.12.2 Config or crafttweaker method to add heat sources

### ISSUE THREAD

**Issue by Foreck1** [ZengineeringTeam/Foundry#57]
As stated in the title, the ability to add blockstates as valid heat sources would make for useful intercompatibility options for modpack makers, one such example: 

Better with mods stoked flame 
![image](https://user-images.githubusercontent.com/47757429/84839536-3fd0d180-b00b-11ea-9ff1-2d30d60e7ba7.png)

**Comment by Snownee** [comment]
```
Heating.addStateSource(state, heat_value);
```

Also added configurable molding material

**Comment by Foreck1** [comment]
Thanks a lot! to be sure, do I declare "state" as a string or as an IIblockState using bracket handlers?

**Comment by Snownee** [comment]
IBlockState

**Comment by ScienceDrummer** [comment]
I was wondering what the new update added lol
