### ISSUE TITLE
AddMold not working, or I just dont understand it

### ISSUE THREAD

**Issue by ghost** [ZengineeringTeam/Foundry#61]
* Minecraft Version: 1.12.2
 * Mod Version: 1.7.17

Hi, Im trying to add an item into the game and register it as a mold.  I've successfully added the item using ContentTweaker
But when I try `mods.foundry.Casting.addMold(<contenttweaker:mold_pearl>);`   I get No Such Method AddMold

The adding of my item is in a separate script to my foundry script

I am new to ZenScript so please be gentle

This is the ContentTweaker AddItem script  https://pastebin.com/pMuCGucE
Here is the crafttweaker log  https://pastebin.com/ydf9nubT
I am using ShadowsOfFire wiki   https://github.com/Shadows-of-Fire/Foundry/wiki/Crafttweaker-Support

**Comment by democat3457** [comment]
I believe addMold is no longer used. Its replacement is `mods.foundry.Casting.addRecipe(output, input, mold)` so the mold is used directly in the addition of a casting recipe.

**Comment by ghost** [comment]
Thank You, Thank You, Thank You

Works perfectly
